[package]
name = "firecracker"
version = "0.1.0"
edition = "2021"

[dependencies]
robot_serial = { git = "ssh://git@github.com/EMU5-Robotics/transport.git", rev = "3a55e13f218f72d73a440a803e5cc32e5db3413f" }
log = "0.4.22"
env_logger = "0.11.5"
