[package]
name = "firecracker"
version = "0.1.0"
edition = "2021"

[dependencies]
robot_serial = { git = "ssh://git@github.com/EMU5-Robotics/transport.git", rev = "994fd07da70f95300c077c7f1b5a9c535df5b2a5" }
log = "0.4.22"
env_logger = "0.11.5"
