[package]
name = "firecracker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "big"
path = "src/big_robot.rs"

[[bin]]
name = "small"
path = "src/small_robot.rs"

[dependencies]
robot_serial = { git = "ssh://git@github.com/EMU5-Robotics/transport.git", rev = "3a55e13f218f72d73a440a803e5cc32e5db3413f" }
communication = { git = "ssh://git@github.com/EMU5-Robotics/communication.git", rev = "02f0a275ff1b7758f70471fa28eccca304cd9a25" }
log = "0.4.22"
