[package]
name = "firecracker"
version = "0.1.0"
edition = "2021"

[dependencies]
robot_serial = { git = "ssh://git@github.com/EMU5-Robotics/transport.git", rev = "019726eff048f8e092bbbf380992480c69e30b63" }
log = "0.4.22"
env_logger = "0.11.5"
